org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.7-beta
neo_version_range=[26.2.0.7-beta,)

mod_id=crackerslib
mod_name=CrackersLib
mod_license=All Rights Reserved
mod_version=26.2-0.4.6
maven_dir=snapshots
mod_group_id=nonamecrackers2.crackerslib
mod_authors=nonamecrackers2
mod_description=Contains a bunch of helpful code for nonamecrackers2s mods