modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="crackerslib"
version="0.0"
displayName="CrackersLib"
authors="nonamecrackers2"
description='''
Contains a bunch of helpful code for nonamecrackers2's mods
'''

[[dependencies.crackerslib]] #optional
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.crackerslib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
