modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="crackerslib"
version="0.0"
displayName="CrackersLib"
authors="nonamecrackers2"
description='''
Contains a bunch of helpful code for nonamecrackers2's mods
'''

[[dependencies.crackerslib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.crackerslib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
